 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/forums", type: :request do
  # Forum. As you add validations to Forum, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Forum.create! valid_attributes
      get forums_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      forum = Forum.create! valid_attributes
      get forum_url(forum)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_forum_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      forum = Forum.create! valid_attributes
      get edit_forum_url(forum)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Forum" do
        expect {
          post forums_url, params: { forum: valid_attributes }
        }.to change(Forum, :count).by(1)
      end

      it "redirects to the created forum" do
        post forums_url, params: { forum: valid_attributes }
        expect(response).to redirect_to(forum_url(Forum.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Forum" do
        expect {
          post forums_url, params: { forum: invalid_attributes }
        }.to change(Forum, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post forums_url, params: { forum: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested forum" do
        forum = Forum.create! valid_attributes
        patch forum_url(forum), params: { forum: new_attributes }
        forum.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the forum" do
        forum = Forum.create! valid_attributes
        patch forum_url(forum), params: { forum: new_attributes }
        forum.reload
        expect(response).to redirect_to(forum_url(forum))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        forum = Forum.create! valid_attributes
        patch forum_url(forum), params: { forum: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested forum" do
      forum = Forum.create! valid_attributes
      expect {
        delete forum_url(forum)
      }.to change(Forum, :count).by(-1)
    end

    it "redirects to the forums list" do
      forum = Forum.create! valid_attributes
      delete forum_url(forum)
      expect(response).to redirect_to(forums_url)
    end
  end
end
