default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  host: localhost
  password: 2659
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: be_free_development

test:
  <<: *default
  database: be_free_test

production:
  <<: *default
  database: <%= ENV['DATABASE'] %>
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>
  host: <%= ENV['HOST'] %>
  URI: <%= ENV['HOST'] %>